# Global settings applied to the whole site.
[build]
  publish = "dist"
  command = "npm run build:prod"

# Production context: All deploys to the main
# repository branch will inherit these settings.
[context.production]
  command = "npm run build:prod"
  [context.production.environment]
  API_URL = "https://api.hittaskyddsrum.se/api/v1"
  GA_ACCOUNT = "UA-49029089-1"
  GMAPS_API_KEY = "AIzaSyDmgFCTblHgx6hZmxZyeaFgDazciC3ur4k"
  SENTRY_KEY = "df5f6919607346d3ba4d8174bedb8dad"
  SENTRY_PROJECT = "190959"
  [context.production.environment]
  API_URL = "https://api.hittaskyddsrum.se/api/v1"
  GA_ACCOUNT = "UA-49029089-1"
  GMAPS_API_KEY = "AIzaSyDmgFCTblHgx6hZmxZyeaFgDazciC3ur4k"
  SENTRY_KEY = "df5f6919607346d3ba4d8174bedb8dad"
  SENTRY_PROJECT = "190959"

[context.stage]
  command = "npm run build:prod"
  [context.stage.environment]
  GMAPS_API_KEY = "AIzaSyA3kjCWox3nKYBjpMPECalvCVqvldePykU"

[context.deploy-preview]
  [context.deploy-preview.environment]
  API_URL = "https://api.hittaskyddsrum.se/api/v1"
  GMAPS_API_KEY = "AIzaSyDmgFCTblHgx6hZmxZyeaFgDazciC3ur4k"
  SENTRY_KEY = "df5f6919607346d3ba4d8174bedb8dad"
  SENTRY_PROJECT = "190959"
